
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 11 12:42:58 PDT 2018
//----------------------------------------------------

package tools.parsers.Expression;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int GEQ = 12;
  public static final int AND = 16;
  public static final int LOW = 29;
  public static final int LT = 9;
  public static final int PLUS = 3;
  public static final int CSEARCH = 22;
  public static final int OR = 17;
  public static final int RPAREN = 8;
  public static final int PHENOTYPE = 20;
  public static final int ASSN = 14;
  public static final int SEMI = 2;
  public static final int NOT = 18;
  public static final int UPPER = 27;
  public static final int IMPLIES = 19;
  public static final int VIRTUAL = 25;
  public static final int LPAREN = 7;
  public static final int GT = 10;
  public static final int ID = 32;
  public static final int STRING = 34;
  public static final int LOWER = 26;
  public static final int COMMA = 15;
  public static final int NUMBER = 31;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int MED = 30;
  public static final int RSEARCH = 23;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int HIGH = 28;
  public static final int EQ = 13;
  public static final int LEQ = 11;
  public static final int THRESHOLD = 24;
  public static final int SEARCH = 21;
  public static final int TMPID = 33;
}

