/* Generated By:JavaCC: Do not edit this line. GMLConstants.java */
package tools.graphs.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GMLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHA_CHAR = 1;
  /** RegularExpression Id. */
  int NUM_CHAR = 2;
  /** RegularExpression Id. */
  int SIGN = 3;
  /** RegularExpression Id. */
  int ALPHANUM_CHAR = 4;
  /** RegularExpression Id. */
  int ID_CHAR = 5;
  /** RegularExpression Id. */
  int ID = 6;
  /** RegularExpression Id. */
  int REAL_B = 7;
  /** RegularExpression Id. */
  int REAL_E = 8;
  /** RegularExpression Id. */
  int REAL_S = 9;
  /** RegularExpression Id. */
  int WHITESPACE = 10;
  /** RegularExpression Id. */
  int GRAPH = 14;
  /** RegularExpression Id. */
  int NODE = 15;
  /** RegularExpression Id. */
  int EDGE = 16;
  /** RegularExpression Id. */
  int INTEGER = 17;
  /** RegularExpression Id. */
  int REAL = 18;
  /** RegularExpression Id. */
  int IDENTIFIER = 19;
  /** RegularExpression Id. */
  int STRING_START = 20;
  /** RegularExpression Id. */
  int STRING_END = 21;
  /** RegularExpression Id. */
  int STRING_WORD = 22;

  /** Lexical state. */
  int LexString = 0;
  /** Lexical state. */
  int DEFAULT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ALPHA_CHAR>",
    "<NUM_CHAR>",
    "<SIGN>",
    "<ALPHANUM_CHAR>",
    "<ID_CHAR>",
    "<ID>",
    "<REAL_B>",
    "<REAL_E>",
    "<REAL_S>",
    "<WHITESPACE>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"graph\"",
    "\"node\"",
    "\"edge\"",
    "<INTEGER>",
    "<REAL>",
    "<IDENTIFIER>",
    "\"\\\"\"",
    "\"\\\"\"",
    "<STRING_WORD>",
    "\"[\"",
    "\"]\"",
  };

}
